#!/usr/bin/env node

const WS_HOST = '127.0.0.1';
const WS_PORT = 3000;

const WebSocket = require('uws');

var WebSocketServer = WebSocket.Server;
var wss = new WebSocketServer({ port: WS_PORT });

process.on('SIGHUP', () => {
  console.log('Received SIGHUP. Reloading x, y z..');
});
