const Analyser = require('./analyser.js');

const example_room1 = {"title":"","rooms":[{"room_type_name":"Living Room 810751","position":{"x":0,"y":0}},{"room_type_name":"Conservatory 805634","position":{"x":0,"y":0}},{"room_type_name":"Conservatory 805634","position":{"x":0,"y":0}},{"room_type_name":"Conservatory 805634","position":{"x":0,"y":0}},{"room_type_name":"Living Room 810751","position":{"x":0,"y":0}}],"room_types":{"Living Room 810751":{"name":"Living Room 810751","objects":[{"object_type_name":"block4x2","position":{"x":3,"y":10,"z":21},"rotation":0},{"object_type_name":"centrifuge","position":{"x":29,"y":13,"z":7},"rotation":0},{"object_type_name":"table-low","position":{"x":13,"y":15,"z":20},"rotation":0},{"object_type_name":"spectography","position":{"x":10,"y":16,"z":27},"rotation":0},{"object_type_name":"sink","position":{"x":16,"y":17,"z":9},"rotation":0},{"object_type_name":"bed","position":{"x":12,"y":23,"z":21},"rotation":0},{"object_type_name":"block4x4","position":{"x":9,"y":24,"z":3},"rotation":0},{"object_type_name":"tv","position":{"x":21,"y":4,"z":25},"rotation":0}],"floor_plan":[],"layout":[{"x":0,"y":0},{"x":10,"y":0},{"x":10,"y":10},{"x":0,"y":10}]},"Conservatory 805634":{"name":"Conservatory 805634","objects":[{"object_type_name":"fridge","position":{"x":10,"y":5,"z":21},"rotation":0},{"object_type_name":"block2x1","position":{"x":13,"y":23,"z":1},"rotation":0},{"object_type_name":"growbox","position":{"x":1,"y":16,"z":15},"rotation":0},{"object_type_name":"sink","position":{"x":23,"y":25,"z":22},"rotation":0}],"floor_plan":[],"layout":[{"x":0,"y":0},{"x":10,"y":0},{"x":10,"y":10},{"x":0,"y":10}]},"Box Room 509629":{"name":"Box Room 509629","objects":[{"object_type_name":"block4x4","position":{"x":6,"y":1,"z":13},"rotation":0},{"object_type_name":"sofa","position":{"x":1,"y":26,"z":21},"rotation":0},{"object_type_name":"kettle","position":{"x":6,"y":16,"z":4},"rotation":0},{"object_type_name":"worktop","position":{"x":24,"y":20,"z":6},"rotation":0},{"object_type_name":"block4x2","position":{"x":9,"y":15,"z":26},"rotation":0},{"object_type_name":"worktop","position":{"x":18,"y":22,"z":3},"rotation":0},{"object_type_name":"cupboard","position":{"x":22,"y":17,"z":15},"rotation":0},{"object_type_name":"block1x1","position":{"x":8,"y":3,"z":12},"rotation":0},{"object_type_name":"block1x1","position":{"x":22,"y":22,"z":11},"rotation":0},{"object_type_name":"block1x1","position":{"x":6,"y":1,"z":3},"rotation":0},{"object_type_name":"block4x4","position":{"x":12,"y":25,"z":23},"rotation":0},{"object_type_name":"composter","position":{"x":23,"y":26,"z":17},"rotation":0}],"floor_plan":[],"layout":[{"x":0,"y":0},{"x":10,"y":0},{"x":10,"y":10},{"x":0,"y":10}]}},"size":{"x":0,"y":0}};

const example_room2 = {"title":"","rooms":[{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}},{"room_type_name":"Cloakroom 744753","position":{"x":0,"y":0}}],"room_types":{"Cloakroom 744753":{"name":"Cloakroom 744753","objects":[{"object_type_name":"block4x2","position":{"x":26,"y":8,"z":0},"rotation":0},{"object_type_name":"block2x1","position":{"x":26,"y":5,"z":19},"rotation":0},{"object_type_name":"cupboard","position":{"x":27,"y":24,"z":2},"rotation":0},{"object_type_name":"cooker","position":{"x":22,"y":22,"z":17},"rotation":0},{"object_type_name":"block2x2","position":{"x":14,"y":19,"z":12},"rotation":0},{"object_type_name":"kettle","position":{"x":12,"y":15,"z":25},"rotation":0},{"object_type_name":"microscope","position":{"x":27,"y":28,"z":19},"rotation":0},{"object_type_name":"block2x2","position":{"x":5,"y":6,"z":26},"rotation":0},{"object_type_name":"block1x1","position":{"x":27,"y":17,"z":19},"rotation":0},{"object_type_name":"microscope","position":{"x":3,"y":20,"z":29},"rotation":0},{"object_type_name":"composter","position":{"x":12,"y":6,"z":19},"rotation":0},{"object_type_name":"block4x4","position":{"x":16,"y":13,"z":4},"rotation":0},{"object_type_name":"block8x4","position":{"x":17,"y":15,"z":24},"rotation":0}],"floor_plan":[],"layout":[{"x":0,"y":0},{"x":10,"y":0},{"x":10,"y":10},{"x":0,"y":10}]}},"size":{"x":0,"y":0}};

const example_room3 = {"title":"","rooms":[{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}},{"room_type_name":"Ballroom 451013","position":{"x":0,"y":0}}],"room_types":{"Ballroom 451013":{"name":"Ballroom 451013","objects":[{"object_type_name":"block4x4","position":{"x":12,"y":9,"z":15},"rotation":0},{"object_type_name":"spectography","position":{"x":25,"y":23,"z":29},"rotation":0},{"object_type_name":"bed","position":{"x":23,"y":18,"z":28},"rotation":0},{"object_type_name":"block8x4","position":{"x":0,"y":11,"z":13},"rotation":0},{"object_type_name":"block1x1","position":{"x":23,"y":1,"z":11},"rotation":0},{"object_type_name":"shower","position":{"x":13,"y":24,"z":4},"rotation":0},{"object_type_name":"table-low","position":{"x":24,"y":14,"z":5},"rotation":0},{"object_type_name":"kettle","position":{"x":19,"y":13,"z":26},"rotation":0},{"object_type_name":"cupboard","position":{"x":9,"y":9,"z":21},"rotation":0},{"object_type_name":"fridge","position":{"x":21,"y":5,"z":16},"rotation":0},{"object_type_name":"kettle","position":{"x":2,"y":0,"z":8},"rotation":0},{"object_type_name":"block4x4","position":{"x":26,"y":2,"z":21},"rotation":0},{"object_type_name":"block2x2","position":{"x":28,"y":2,"z":5},"rotation":0},{"object_type_name":"growbox","position":{"x":24,"y":25,"z":22},"rotation":0},{"object_type_name":"block4x2","position":{"x":1,"y":25,"z":27},"rotation":0},{"object_type_name":"cupboard","position":{"x":14,"y":29,"z":27},"rotation":0},{"object_type_name":"fridge","position":{"x":26,"y":13,"z":3},"rotation":0}],"floor_plan":[],"layout":[{"x":0,"y":0},{"x":10,"y":0},{"x":10,"y":10},{"x":0,"y":10}]}},"size":{"x":0,"y":0}};

var layout, result;

console.log('=========== Example Room 1 =============');
layout = Analyser.struct_to_layout(example_room1);
result = Analyser.analyse(layout);
result.log();

console.log('=========== Example Room 2 =============');
layout = Analyser.struct_to_layout(example_room2);
result = Analyser.analyse(layout);
result.log();

console.log('=========== Example Room 3 =============');
layout = Analyser.struct_to_layout(example_room3);
result = Analyser.analyse(layout);
result.log();

